### ISSUE TITLE
Please add missing entries to localize langages for widgets :)

### ISSUE THREAD

**Issue by Keneda-ut** [pavelprosto94/uHome#7]
And do the same for weather standalone install app/widget.

You know why i ask ^^

**Comment by Anne017** [comment]
Should be fixed with these pull requests for internationalization (addition of i18n.tr() in the QML files).
Sorry for the spam, I am sure there is a way to do multiple commits in a single pull request but I am not used to that.
#10 
#11 
#12 
#13 
#14 
#15 
#16 

There is no need to internationalize the OpenWeatherMap widget, a simple [translation](https://github.com/pavelprosto94/openweatermapwidget/pull/1) is possible.

**Comment by Keneda-ut** [comment]
Some choice for translation were intended, for instance i don't like "malin" because it's evil conoted, so i prefer "futé" :)
Anyway, now you're here, so i let you take over.
Would be nice if you were active on ubports forum.

**Comment by pavelprosto94** [comment]
Each widget works as an independent component of the uHome program.
This is done so that the widget files do not conflict with the files of the program itself.
I am working on a custom tool for localizing widgets, since the standard one will not work here.
